export const UPDATE_LONGITUDE = 'UPDATE_LONGITUDE';

export const UPDATE_LATITUDE = 'UPDATE_LATITUDE';

export const UPDATE_DATE = 'UPDATE_DATE';

export const FETCH_WEATHER = 'FETCH_WEATHER';

export const FETCH_WEATHER_SUCCESS = 'FETCH_WEATHER_SUCCESS';

export const FETCH_WEATHER_FAIL = 'FETCH_WEATHER_FAIL';